package com.example.firstvaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.PopupDateField;

public class MyComposite extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private PopupDateField popupDateField_2;



	
	public MyComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("460px");
		mainLayout.setHeight("260px");
		
		// top-level component properties
		setWidth("460px");
		setHeight("260px");
		
		// popupDateField_2
		popupDateField_2 = new PopupDateField();
		popupDateField_2.setImmediate(false);
		popupDateField_2.setWidth("-1px");
		popupDateField_2.setHeight("-1px");
		mainLayout.addComponent(popupDateField_2, "top:120.0px;left:120.0px;");
		
		return mainLayout;
	}
}
